language: python

cache:
  pip: true
  yarn: true

python:
  - "3.5"

install:
  - yarn
  - yarn build
  - pip install -r requirements.txt

script:
  - python manage.py test

services:
  - postgresql
