language: python

cache:
  pip: true
  yarn: true

python:
  - "3.5"

node_js:
  - "10.7"

install:
  - yarn
  - yarn build
  - pip install -r requirements.txt

script:
  - python manage.py test

services:
  - postgresql

addons:
  postgresql: "9.6"
